[workspace]

[package]
name = "truecalc-workbook-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
truecalc-workbook = { path = "..", features = [] }

[[bin]]
name = "fuzz_from_json"
path = "fuzz_targets/fuzz_from_json.rs"
test = false
doc = false

[[bin]]
name = "fuzz_formula_set"
path = "fuzz_targets/fuzz_formula_set.rs"
test = false
doc = false
